name: Build and test

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout mod repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK versions
        uses: actions/setup-java@v4
        with:
          java-version: |
            8
            17
            21
          distribution: 'zulu'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"
          validate-wrappers: true
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Compile the mod
        run: ./gradlew --build-cache --info --stacktrace assemble
      - name: Attach compilation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.repository_id }}-build-libs
          path: build/libs/
          retention-days: 90
      - name: Attach Gradle reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.repository_id }}-reports
          path: build/reports/
          retention-days: 31
